export {default as PerfilScreen} from "./Perfil"
export {default as CarrinhoScreen} from "./Carrinho"
export {default as LoginScreen} from "./Login"
export {default as RegisterScreen} from "./Register"
export {default as RecScreen} from "./Rec"